### ISSUE TITLE
Project fork

### ISSUE THREAD

**Issue by kernc** [mitmproxy/pdoc#182]
Dear Maintainers,

I came across pdoc a couple of months ago and I immediately felt tremendous appreciation for all of its core ideas:

* public identifiers are auto-discovered following common conventions, 
* whole documentation relies on a well-known language feature (docstrings),
* documentation hierarchy follows module hierarchy,
* module docstrings are used to introduce the topic,
* identifiers can easily be referred to with backticks, and
* the default documentation language is a flavor of Markdown which, compared to reST, pretty much everyone knows and adores.
  
This makes it a perfect documentation utility for small, tidy projects.

So it was with an amount of grief I noticed the repository recently took an overhaul which introduced, on balance, quite a few regressions as far as my use cases go. As no new releases have been made, I understand the development is not finished, but it's initial vigour certainly seems _stalled_ at the moment, and the [humble pull request](https://github.com/mitmproxy/pdoc/pull/177) I tried to squeeze in in order to restore some of the  previous behavior got no reviews at all. Today with open source abound, PR negligence certainly doesn't instigate new developer/maintaner activity.
    
Thus, I'd like to take the opportunity to announce I had recently started rapidly applying various sensible changes to [a diverged fork](https://github.com/kernc/pdoc) of this project. The split point was 03b96f4, about right before the package layout was, in my view needlessly, restructured. Elsewhere following your example, I took what I could from the upstream  master (like `--filter` switch and module importing logic), but my vision for the project seemingly differs somewhat in other areas. With the major exception of missing alternative docformats (such as numpydoc/Google), I consider the fork pretty much feature-complete. :smiley: 

I wouldn't be as blunt as to propose you reduce the bus factor of the project back to 1.0, nor that you overwrite your history with this augmented one, but should you by chance decide to ever discontinue maintainership, I'll be happy to take over the project I'll at the time quite likely still be most actively using.

Refs: https://github.com/mitmproxy/pdoc/issues/148

**Comment by cortesi** [comment]
Thanks for letting us know, and we've discussed this somewhat by email.  The bus factor will return to normal as soon as time permits, and in the meantime we'll keep an eye on your repo.

**Comment by untitaker** [comment]
After I filed a bug report against this repo, I was contacted in private by @kernc asking me to try out https://github.com/pdoc3/pdoc, a fork of pdoc, confusingly also named pdoc (sometimes pdoc3). Almost all information linking back to pdoc3's origins have been removed from its docs, the [Python wiki page](https://wiki.python.org/moin/DocumentationTools) has been edited to link to his fork (not necessarily by him) while simultaneously removing the link to @BurntSushi's repo (which redirects to `mitmproxy/pdoc`).


That fork is relicensed under AGPL, which seems to diverge from @BurntSushi's usual license choices. So it can't possibly be called a successor like @kernc tries to make it seem.

For the sake of transparency, @kernc's reasoning for contacting me privately was:

>I was asked not to participate on the tracker so I am writing to you personally.

I have no idea what he meant by that.

**Comment by cortesi** [comment]
Hi there! I'll have a look at the licensing situation. Kernc is very welcome to participate here, but he would have to change his avatar to something that doesn't so closely resemble a swastika.

**Comment by BurntSushi** [comment]
The relicensing is likely perfectly legal. pdoc does use the UNLICENSE after all. If it were the MIT then they would be obliged to retain that license somewhere in the source repository.

Of course, just because it is legal doesn't mean it's right. I consider @kernc's actions here to be rude and unethical. Keeping the same name in a hostile fork is clearly also an exercise in poor judgment.

**Comment by untitaker** [comment]
I noticed the swastika as well, but I wasn't entirely sure if mentioning it would derail the conversation. Thanks for calling him out @cortesi.

I also just noticed that the relicensing removed copyright statements, which is fine for unlicensed code I suppose (just like @BurntSushi said)

**Comment by Rosuav** [comment]
From the point of view of the Wiki, I'd like to just say that it is rather rude to change the link to point to the new fork without even notifying the present maintainers that you have done this. Please exercise some caution when making changes of this nature. I hope that the maintainers of both the original project and the fork can come to some form of agreement about how the projects are to be advertised (for instance, if the fork chooses a new name, both could be listed on the wiki, with an explanation of the distinctions). If consensus is not possible, please do NOT engage in an edit war on the wiki itself, as this will serve only to confuse end users and give everyone involved a bad name (including the wiki, for being untrustworthy).

For the time being, I have reverted the most recent change. I'm going to let the matter be debated here rather than make a strong stance myself, as I'd like to believe that everyone involved can behave maturely and come to an agreement. :)

**Comment by Erotemic** [comment]
So... I just found this project, and I was initially under the impression that this project had moved to pdoc3. The website and repo look extremely well done (and I hate to say it, but it looks more professional than this repo). However, I've come to learn that pdoc3 does not succeed pydoc. If OP continues attempts at overshadowing this repo, something will need to be done. 

I would have kept my initial impression, if I didn't happen to notice two very subtle swastikas in the bottom corners of this page: https://pdoc3.github.io/pdoc/  

At first I didn't believe it, but there it was. In the source it was as clear as day:

```html
<div class="container is-fluid has-text-grey-lighter">
  <span class="is-pulled-left">卐</span>
  <span class="is-pulled-right">卍</span>
  </div>
```

I tried hard to think of some reason that anyone could reasonably use that symbol in modern times. I couldn't. As far as I can tell, the holocaust irreversibly transformed that symbol into one of hatred, fascism, and close-mindedness. I wanted to raise a Github issue, because surely it must be a mistake. I naively wanted to believe that such a talented programmer would be too smart to harbor such views. 

Alas, I did a quick search to see if anyone else noticed the swastikas, and here I am. I saw his avatar and any reasonable doubt dissipated. Sad as it is, even smart people are susceptible to propaganda, racism, and xenophobia, especially if those views are reinforced by friends or family. 

While I'm not holding my breath, I know reform is possible. I truly hope that the OP realizes the immense hatred projected by Nazis symbols, researches and understands the effect that those symbols have on others, makes any effort to empathize with those who were and are victimized Nazis, and chooses to disengage from whatever groups or culture would glorify baseless hatred of other human beings.

Shit. It's so frustrating that we need to sully what could be an otherwise lovely technical conversation with such unpleasant topics. But its just not ok for anyone in this modern age to think it's acceptable to wield that imagery so lightly. 

@kernc please take my words to heart. Change your avatar, reevaluate the reason why you chose it, take down the deceptive fork, and come back and help develop this repo. You seem so intelligent, and everyone makes mistakes. I know that you're smart enough to see though and cast off that fallacious ideology, please make the effort.

**Comment by kernc** [comment]
> because surely it must be a mistake. I naively wanted to believe that such a talented programmer would be too smart to harbor such views.

Man, thanks for the kind words! :heart: Hate to have to say it, but your initial gut instinct was correct and the later conclusion was not.

**Comment by cortesi** [comment]
Sorry, this is not a conversation we want to host here.
