### ISSUE TITLE
Pdoc to accept scripts/modules with the `input()` function

### ISSUE THREAD

**Issue by StrangeRanger** [mitmproxy/pdoc#228]
#### Problem Description

_To be honest, I'm not sure if this is a bug or not, but I'm assuming it isn't._
If I run pdoc on a module or script that uses the `input()` function, pdoc produces an `EOF when reading a line` error. 

#### Proposal
I'm not sure why pdoc produces an error if `input()` is used, but if possible, allow pdoc to accept modules/scripts that include `input()` in the code.

**Comment by mhils** [comment]
What would you expect pdoc to do? 

Some background: pdoc needs to execute the file to parse it contents. It currently closes sys.stdin before doing so to signal that there won't be user input available. When your script executes `input()` as part of the import process, input will complain that stdin is closed and raise the error you mentioned above. There aren't many viable alternatives. We don't want to make it interactive, but we also can't provide "fake input", which in some cases could trigger infinite loops. Console tools already often check if stdin is closed and behave differently if so. IMO the proper fix here is that you guard your start code so that it is not executed on import:

```python
der foo(): ... # your normal methods

if __name__ == "__main__":
    x = input("Input a number. ")
```

See more: https://stackoverflow.com/questions/419163/what-does-if-name-main-do

**Comment by StrangeRanger** [comment]
Ok, that makes sense. I'll try using that as a possible alternative for future projects when using pdoc.

**Comment by StrangeRanger** [comment]
@mhils I found out recently that pdoc3 was able to implement it so that it's run the script by default in a way where it would accept user input. Is there a way you could do something similar?

**Comment by StrangeRanger** [comment]
I think there are even ones that skip over the user input, instead of just producing an error.

**Comment by mhils** [comment]
@StrangeRanger: What kind of behavior do you expect? Do you want it to prompt for input while running pdoc?

I don't know what pdoc3 is doing, nor will I look at it because it's AGPL-licensed.

**Comment by StrangeRanger** [comment]
I'd expect pdoc to recognize when the code requires user input, then allow the user to enter whatever they need to enter, while pdoc is running. Either that or pdoc completely ignores the input or provides some kind of arbitrary input.

**Comment by mhils** [comment]
I strongly believe that pdoc should not interactively prompt for input. If we do that, pdoc can just appear stuck. Is there a particular reason why you don't want to adjust your code to add a [`if __name__ != "__main__"`](https://docs.python.org/3/library/__main__.html) guard?

**Comment by StrangeRanger** [comment]
I don't usually use `if __name__ != "__main__"`/`if __name__ == "__main__"`, and it'd get quite annoying if I had to do that for every single program that took input. I'd continuously have to move the code inside and outside of the if statement, and over time I'd just get sick of doing that.

**Comment by StrangeRanger** [comment]
Is it not possible to get pdoc to ignore the input request or just give it an arbitrary number or string?

**Comment by mhils** [comment]
Not really - we can't return arbitrary strings because that makes us run into endless loops. Your application either needs to check if stdin is open or if `__name__ == "__main__"`. Put differently, if you document your Python modules, it would be nice if they could just be imported without requiring any user input.

I'm sorry that this makes your use case more difficult, but I think the current behavior is the correct one. I want pdoc to stay sufficiently lean, and that only works by rejecting some proposals. You can of course also maintain your own fork with [these two lines](https://github.com/mitmproxy/pdoc/blob/5fc8fcc310ba5b9f247e196c8db427e3943f8245/pdoc/extract.py#L57-L58) commented out. :)

**Comment by StrangeRanger** [comment]
Alright. I appreciate you taking the time to reply back to this issue.
