### ISSUE TITLE
Inconsistent module names when specifying multiple paths

### ISSUE THREAD

**Issue by mhils** [mitmproxy/pdoc#325]
I have one related question about the html output after running the [above script.](https://github.com/mitmproxy/pdoc/issues/322#issuecomment-1002280227)

```Python
# script full path: C:\Dropbox\python\create_pdoc.py
import pdoc
from pathlib import Path
myscripts = ["./myscript.py", "./path2/myscript.py", "./myscript3.py"]
pdoc.pdoc(*myscripts, output_directory=Path("./_mydocs"))

```
I run this script calling `C:\python38\python C:\Dropbox\python\create_pdoc.py`
The .py scripts to be documented are in the same `C:\Dropbox\python\` folder (or children folders, like the script inside `path2` subfolder).  I don't think their content is relevant for this question (they just contain a sample function definition followed by a docstring comment: `""" my comments """`).

As expected, the output (3 html documents + index.html + search.js) is created in `C:\Dropbox\python\_mydocs`
And `index.html` left menu shows links to the other 3 html docs in same order as they are in `myscripts` list, like this:
#### Available Modules
- Dropbox.python.myscript
- myscript
- Dropbox.python.myscript3

What I don't understand is the reason why the 2nd one (located inside path2) shows **no path** information, while the 1st and 3rd (located in the same folder as my create_pdoc.py script) show the **full path** below C: (i.e. **Dropbox.python.**)

How can I control that? I would have expected one of these results instead:
#### Available Modules
- myscript
- path2.myscript
- myscript3
#### Available Modules
- Dropbox.python.myscript
- Dropbox.python.path2.myscript
- Dropbox.python.myscript3

... either **all** or **none** scripts preceded by **Dropbox.python.** path (although I would prefer **not** to show it)

_Originally posted by @abubelinha in https://github.com/mitmproxy/pdoc/issues/322#issuecomment-1003104131_

**Comment by mhils** [comment]
@abubelinha: Yeah, that does not look right. I'll need to take a look, but not before next year. :)

**Comment by abubelinha** [comment]
Sorry, I should have created a new issue myself.
Thanks and happy new year's eve!

**Comment by mhils** [comment]
I cannot reproduce this locally at all. Would you mind sharing a ZIP archive with a small example, and also specify from which working directory you are invoking `C:\python38\python C:\Dropbox\python\create_pdoc.py`?

**Comment by abubelinha** [comment]
Thanks for looking at this @mhils 

First of all, let me say there is a longer pathname between `C:` and `\Dropbox\python\` but I'll replace with `...` 
i.e. when I write `C:\...\Dropbox\python\` it really is `C:\some\more\stuff\including\my\full\name\blah\blah\Dropbox\python\`
Also, when I said `path2` it really was `_path2` (see the examples below)
I don't think this makes any difference for the issue. Do you?

When trying to generate you a example to zip, I discovered something else.
Depending on the path where I put my example, results are different. 
But in both cases they look somehow buggy to me.

When we opened the issue, I was invoking the script like this:
`C:\...\Dropbox\python>C:\python38\python C:\...\Dropbox\python\create_pdoc.py`
`C:\...\Dropbox\python>C:\python38\python create_pdoc.py`
Either way, that resulted in:

**Available Modules**
- Dropbox.python.myscript
- myscript                                     <--- the one inside a subpath
- Dropbox.python.myscript3

Today I tried to put all the example inside a `_pdoc_issue_325 folder`, which contains `_mydocs` and `_path2` subfolders.
So I invoked the script like this:
`C:\...\Dropbox\python\_pdoc_issue_325>C:\python38\python create_pdoc.py`
`C:\...\Dropbox\python\_pdoc_issue_325>C:\python38\python C:\...\Dropbox\python\_pdoc_issue_325\create_pdoc.py`

Either way, that resulted in:

**Available Modules**
- myscript                                     <--- the one inside a subpath
- myscript3

So, no path information this time, and also now one `myscript` is missing (the one located at the same level as `myscript3`).

I generated two zip files, so you can see not only the scripts, but also the output documentation.
[executed_from_C...Dropbox.python.zip](https://github.com/mitmproxy/pdoc/files/7815387/executed_from_C.Dropbox.python.zip)
[executed_from_C...Dropbox.python._pdoc_issue_325.zip](https://github.com/mitmproxy/pdoc/files/7815389/executed_from_C.Dropbox.python._pdoc_issue_325.zip)

**Comment by mhils** [comment]
I have taken `executed_from_C...Dropbox.python.zip` and extracted the contents to `C:\repro`. Next, I opened a PowerShell commandline and entered `cd C:\` followed by `C:\Python310\python.exe C:\repro\create_doc.py`. This creates a `C:\_mydocs` folder with `myscript` and `myscript3` only. I then deleted `C:\repro\_mydocs` and tried `cd C:\repro` followed by `C:\Python310\python.exe create_doc.py`. In this case I also only get a `C:\repro\_mydocs` folder with  `myscript` and `myscript3`. I never get to reproduce the full `Dropbox....` path

---------------------------

> So, no path information this time, and also now one myscript is missing (the one located at the same level as myscript3).

Yes, I think this is expected behavior - pdoc cannot document two modules with the same name at the same time. I'll see if we can add as simple warning though.

**Comment by mhils** [comment]
I've added a warning in 69c900f. :)

**Comment by abubelinha** [comment]
This is pretty odd.
I was also unable to to replicate the first described behaviour using another very similar path ... it just happens in that path (which is where most of my scripts are located ... I can't change it because many automatic tasks would stop working).

And right now, when I launch again the script from that path, it keeps producing the same results (so it was not a mistake of me when I created the issue). 
Did you look at the html files included in the first zip? ... for some reason, pdoc was/is "able" to document two modules with the same name (using the Dropbox.python prefix). 

Could be something related to my previous try of installing pdoc3? (shared libraries, or whatever) 
It is not installed anymore. Anyway, that wouldn't explain the different behaviour in different paths, I think.
I have just uninstalled pdoc, reinstalled, and it keeps happening. 

Could be something related of this being inside a Dropbox shared folder?
But the other subpaths I tried are also inside anyway.

... I'm going nuts

**Comment by mhils** [comment]
Do you perhaps have `__init__.py` files somewhere in your Dropbox folder or in your path leading there?

**Comment by abubelinha** [comment]
Yes, that was it !!!
A `C:\...\Dropbox\python\__init__.py` file, dated almost a year ago.
I renamed it to `__in-it__.py` and now pdoc behaves as you expected.

Also, it is an empty file. Not sure about the reason for it to be there, though. Perhaps needed by some other library? I guess this could make some other script stop working.
I would like to understand why `__init__.py` interferres with pdoc work.

**Comment by mhils** [comment]
Excellent, thanks for confirming. The latest release now also warns if you specify two files with the same name, so this issue can be closed. :)

**Comment by abubelinha** [comment]
Yes, but I would like to understand the role of `__init__.py` in pdoc's work.
Now that I recovered from going nuts, I feel it was somehow making a good job for my use case. 

I am documenting a list [] of almost-standalone scripts, which are located in different paths (I say almost-standalone because sometimes the script could call another script inside the same folder -i.e. a `config.py` or whatever-). 
In this process, it could happen that two different `config.py` files are found in the list.

Perhaps this is a rather odd usage, but in this context the current "__init__.py issue" permitted pdoc to effectively document two scripts with the same name at different locations.

Knowing that, I feel this could be the way to control the process:

**Available Modules** (when `__init__.py` was found in `C:\...\Dropbox\python`)
- Dropbox.python.myscript    <--- pdoc adds prefix because an `__init__.py` was also found in that path ???
- myscript
- Dropbox.python.myscript3  <--- pdoc adds prefix because an `__init__.py` was also found in that path ???
 
**Modifications:**
1. Changed myscripts = ["./myscript.py", "./path1/myscript1.py", "./path2/myscript.py", "./myscript3.py"]
2. Moved `__init__.py` from `C:\...\Dropbox\python` to its `_path2` subfolder
3. Created a `_path1` subfolder, and added a `myscript1.py` plus another empty `__init__.py`
4. Re-run `C:\...\Dropbox\python>C:\python38\python create_pdoc.py`
5. Output:

**Available Modules** (after modifications):
- myscript
- _path1.myscript1
- _path2.myscript
- myscript3

So, I guess this could be a recommended solution when documenting a list of scripts like mine:
- Do not have an `__init__.py` in your root folder
- Include an `__init__.py` in every subfolder which could contain a script name which might be repeated in the list.
- Do also include an `__init__.py` in **every** subfolder if you want the documented scripts to show a path prefix (left frame of index.html)

Do you agree @mhils?  I ask for confirmation because I have no idea of what counter side effects could have those added `__init__.py` files (taking in account they affect `pdoc` behaviour, they could affect something else ... but hopefully not standalone scripts like mine).

**Comment by mhils** [comment]
I think you should read https://docs.python.org/3/tutorial/modules.html, in particular the section on `__init__.py`. If you place a `__init__.py` in `directoryA`, pdoc will treat that directory as a module, so a file named `foo.py` will be `directoryA.foo`. So yes, that can be used to resolve naming conflicts. Either way, I would recommend to have everything in a Python packages and not work with scattered script files. :)

**Comment by abubelinha** [comment]
I am a final user more than all ... and Python is already solving my needs amazingly fast even using it this messy way. Fortunately, I have discovered pdoc and it's helping me **a lot** in order to document all my messy scripts.
I am so far away from being a decent software developer, but thanks a lot for the advice. I'll try to read that section ASAP.

**Comment by abubelinha** [comment]
Thanks again @mhils for answering this [comment](https://github.com/mitmproxy/pdoc/issues/318#issuecomment-1007979591). 
So, I understand pdoc default behaviour renders indented module members names in left index.html

Then, should't left index.html be like this in the above examples? (every script contains a "`def myfunction`")

**Available Modules**
- myscript
  - myfunction
- _path1.myscript1
  - myfunction
- _path2.myscript
  - myfunction
- myscript3
  - myfunction

But instead, the generated left index is missing all `myfunction` names. Why so?

**Comment by mhils** [comment]
The module index (intentionally) only shows top-level module names. :)

**Comment by abubelinha** [comment]
Ah ok ... Sorry, I was misunderstanding it. 
Would that be somehow [configurable changing a certain template](https://pdoc.dev/docs/pdoc.html#editing-pdocs-html-template) in my installed pdoc copy?

**Comment by abubelinha** [comment]
I played a bit with jinja2 templates (first time in my life).

- As for **showing the module name in top of left tree**, I could solve it myself adding `<h4>{{ module.fullname }}</h4>` somewhere around [line 750 of my module.html.jinja2](https://github.com/mitmproxy/pdoc/blob/827abe8305acad8d7b4c4b7d8f59b43dde6eb5c3/pdoc/templates/default/module.html.jinja2#L750) (my version may already be outdated because line numbers do not match).

- Not as lucky **showing the modules tree in my module index**, I guess I should create a loop inside [these lines of index.html.jinja2](https://github.com/mitmproxy/pdoc/blob/main/pdoc/templates/default/index.html.jinja2#L37):
```
{% for submodule in all_modules %}
    <li><a href="{{ submodule.replace(".","/") }}.html">{{ submodule }}</a></li>
    {# How can get a list of submodule members here? #}
{% endfor %}
```
Tried `{% for children in submodule %}`, `{% for children in submodule.own_members %}` ... but didn't work (I guess `submodule` is just a string). 

Any hints?
