### ISSUE TITLE
Render Markdown checkboxes as HTML

### ISSUE THREAD

**Issue by mueller-ma** [mitmproxy/pdoc#371]
#### Problem Description

In the main file of a Python lib I include the Readme as doc string:
````python
"""
.. include:: ../README.md
"""
````

The Readme has some markdown checkboxes:

````
- [X] foo
- [ ] bar
````

In the html docs generated by `pdoc --force --html -o ./docs <lib>` these checkboxes aren't rendered as html checkbox, but just as a pair of square brackets.

#### Proposal
Render Markdown checkboxes as HTML checkboxes.

**Comment by mhils** [comment]
pdoc uses `markdown2` for Markdown processing. It looks like markdown2 got a `task_list` extra (https://github.com/trentm/python-markdown2/wiki/Extras). Could you try adding that [here](https://github.com/mitmproxy/pdoc/blob/d2169a3690f07aee138c6ff34f53e5b80fb1a55b/pdoc/render_helpers.py#L41) and send a PR if it works?

**Comment by mhils** [comment]
Disregard my previous comment, we already do include the `task_list` extra. I also get checkboxes using the example you posted:

![image](https://user-images.githubusercontent.com/1019198/161529294-0fdc5e5f-55c7-45b1-b322-1b87d62554fc.png)

The bullet points before the checkboxes aren't ideal, but fixing this is not so straightforward as markdown2 doesn't apply a top-level class on the `ul` element. In either case, checkboxes should render already. Could you clarify what your issue is?

**Comment by mueller-ma** [comment]
I'm sorry, we used an outdated version of pdoc. With the latest version the checkmarks are rendered correctly.
