### ISSUE TITLE
Naming Style Consistent

### ISSUE THREAD

**Issue by Max-ChenFei** [mitmproxy/pdoc#387]
Hi, when I look through the source code and document online, I found most cases, the name of the attributes is snake case, like `own_members,  class_variables, instance_variables`, but `classmethods, staticmethods ` are not.
Are there concerns regarding this?

I am happy to submit the PR and keep the naming style consistent.

**Comment by mhils** [comment]
The reason why `classmethod` and `staticmethod` don't include an underscore is because the underlying Python decorators (`@classmethod`, `@staticmethod`) don't include an underscore either. Maybe they would get one if they were invented today, but as a historical artifact they don't. pdoc follows the naming convention from Python here. I don't think that's too bad (Python programmers are used to seeing `staticmethod` and not `static_method`), so I don't think we should change it. :)
