### ISSUE TITLE
Support GitHub Flavored Markdown or at least CommonMark

### ISSUE THREAD

**Issue by f3ndot** [mitmproxy/pdoc#401]
#### Problem Description

Given the proliferation and ubiquity of GitHub, I believe many unassuming developers (myself included) naively believed what Markdown syntax is supported on GH is part of the original 2004 Markdown spec. Even *if* developers knew the difference, that they would prefer GitHub as that's what's most common. https://github.com/mitmproxy/pdoc/issues/64 suggests this conflation is a problem.

I personally stumbled across then when I wanted a URL to automatically be hyperlinked with `pdoc`, not realizing the [original spec](https://daringfireball.net/projects/markdown/syntax#autolink) requires the URLs to be wrapped in `<` and `>` characters. In a phrase: I've become spoiled by GFM.

#### Proposal

Support the [GitHub Flavored Markdown spec](https://github.github.com/gfm/).

This can take place in a few possible ways:

* via a new `-d gfm` or `-d github-markdown` flag, reserving the `-d markdown` flag for the original 2004 spec
* replace the Markdown support in `pdoc` with the GFM version by default, optionally exposing a `-d original-markdown` for the 2004 spec
* A "pick n choose" approach where the most popular/used parts of GFM are supported on top of the current Markdown implementation (I don't really advocate for this one)

#### Alternatives

I guess not supporting GFM at all?

Independent of my proposal, `pdoc` should probably declare what version or flavour we colloquially know/call as "Markdown". The original is from 2004 released as a Perl script and has remained largely unchanged, warts and all. 

[CommonMark](https://spec.commonmark.org/) appears to be the, well, *common* and well-defined and *versioned*  specification of the original Markdown. Indeed, GFM is derived from CommonMark!

I would hope that `pdoc` would choose a version of the CommonMark spec and support that version explicitly.

#### Additional context

The [Differences from original Markdown](https://github.com/commonmark/commonmark-spec/#differences-from-original-markdown) section of [commonmark-spec](https://github.com/commonmark/commonmark-spec)'s README is enlightening.

**Comment by f3ndot** [comment]
Thanks for responding so quickly! You raise some compelling points, and I can see how that's led to the current state of the project. 

Would you consider then letting the user decide by taking advantage of extras? e.g.:

* `pip install pdoc` is current behaviour
* `pip install pdoc[cmarkgfm]` (or similarly named) for those who are willing to opt in to maybe having to compile due to missing binary wheels

Under this regime you could also offer a `pip install pdoc[commonmark]` is for those who wish to use CommonMark, even if it lacks some extensions you like.

> We enable the [link-patterns](https://github.com/trentm/python-markdown2/wiki/link-patterns) extra to auto-link URLs.

Hey, I mean, that's nice :)

I think this may reveal a greater issue of what *I* want and may find reasonable conflicts with what other's want and find reasonable. For every person who doesn't want `<>` required, I'm sure there are others who would prefer the explicitness.

Maybe this should be another discussion/issue, but I think the markdown2 extensions `pdoc` enables should be user-configurable with pdoc choosing sane defaults. Could be CLI flags, could be `pdoc.ini`, could be whatever makes sense with the least amount of pain. What do you think?

**Comment by mhils** [comment]
> Would you consider then letting the user decide by taking advantage of extras?

I would be very hesistant to do that because it adds additional complexity[^1] and long-term maintenance overhead. We need to keep in sync with multiple other Markdown implementations[^2], which have different feature sets.[^3] I don't think the benefit justifies the costs.

> Could be CLI flags, could be pdoc.ini, could be whatever makes sense with the least amount of pain. What do you think?

One objective for pdoc is to be simple and not require any configuration. Adding additional configuration knobs works against this goal. From my experience, good documentation is usually not held back by a lack of doc tool configuration options. As mentioned in the README, there comes a point where you want to check out [Sphinx](https://www.sphinx-doc.org/) instead if you require more customizability. We provide a set of command line options for the most common needs, but I don't personally think this crosses the bar. Sorry. :)

If you strongly prefer GFM, you can of course always use pdoc as a library:

```python
#!/usr/bin/env python3
import sys

import cmarkgfm
from pdoc import render
from pdoc.__main__ import cli

render.env.filters["to_html"] = cmarkgfm.github_flavored_markdown_to_html
cli(sys.argv[1:])
```

The implicit downside is that this is code you need to maintain yourself. 😉 

[^1]: Simply using extras doesn't work because we can't assume a clean venv with pdoc.
[^2]: See e.g. https://github.com/Zopieux/py-gfm: *"The maintainer is also fatigued by Markdown's library constantly breaking their internal API with each minor release."*
[^3]: For example, cmarkgfm doesn't generate a table of contents datastructure as we use it in the menu. Now you also need to communicate to users under which circumstances this might be missing...

**Comment by daniele-niero** [comment]
Hello @mhils 

Mayabe a silly a question, but is `render.env.filters["to_html"] = cmarkgfm.github_flavored_markdown_to_html` all it takes to use a different markdown backend?

I'm using https://github.com/executablebooks/markdown-it-py for other things and if I could just whoe-horn it into pdoc (at my peril, of course) would make things more consistent for us.
We want a Commonmark and expandable markdown library, so we would really prefer markdown-it-py over markdown2 (despite the horrible name)

**Comment by daniele-niero** [comment]
Well, it just worked! 
Maybe I will find some issues later, but this is great so far. 
I think you should put it in the documentation, as an unsupported but possible option. :)

**Comment by mhils** [comment]
Done, thanks for the good suggestion! :)
