### ISSUE TITLE
Public/private view

### ISSUE THREAD

**Issue by Hibou57** [mitmproxy/pdoc#43]
I patched my local installation so that is provides either a public view or a private view of a module.

The rational is that it's useful to see the documentation of a module's private items to review/work-with/understand it.

I'm using a query string for this: `?private=false` or `?private=true`. I would like to know if it seems OK to use a query string or if the option should appears in the base URL.

I will wait for the review of the already pending pull-requests before I add this patch to my fork and do a pull-request from it.

Also just wanted to say I like _pdoc_, it really helps me, although I had to fix it in multiple ways (my issue is that I don't really know if my fixes are required to me only or if they are of interest to some others too).

**Comment by BurntSushi** [comment]
@Hibou57 Thank you for your recent flurry of activity. I've seen some of it, but I probably won't have time to review it more closely for at least another week.

With that said, I'm unlikely to support a public/private view. It's a corner case IMO and I want to resist increasing the size of `pdoc` as much as feasible. The very existence of `pdoc` is due to the complexity of alternative tools.

**Comment by Hibou57** [comment]
OK, I see. So I guess patch #3 named “Adding a local modules list” will not be good.

In the future, I may just propose this kind of patches to my fork only and not make pull-request for these ones.

**Comment by cortesi** [comment]
I think for now pdoc will remain focused on providing excellent, clean documentation for a public API. Thanks!
