### ISSUE TITLE
Apps Aren't Loaded Yet errors

### ISSUE THREAD

**Issue by lanshark** [mitmproxy/pdoc#644]
#### Problem Description

This is a django app - trying to document the API which is found in ms/views.py.

Trying to run `PYTHONPATH=. pdoc path/file.py -o html` I get the exception: 

AppRegistryNotReady: Apps Aren't Loaded Yet

No error if I omit the -o html

#### Steps to reproduce the behavior:
1. cd to my project home (all paths are relative) in a docker container
2. run pdoc ms/views.py -o html
3. Get the error

#### System Information
Paste the output of "pdoc --version" here.
pdoc: 14.1.0
Python: 3.10.10
Platform: Linux-5.15.49-linuxkit-pr-x86_64-with-glibc2.31

**Comment by mhils** [comment]
This is a bug raised by your code when it's imported, not in pdoc. The problem is that the order in which pdoc imports your modules is different from the order they are typically imported, and your application cannot handle this. One fix might be to try something like 
```
pdoc parent_module !parent_module parent_module.views
```
so that pdoc's import order matches the rest of your app.
